### PR TITLE
Feature/decode std array

### PR DESCRIPTION
**Pull request by theodelrieu**
Hello,

After all, there was absolutely no need to touch the interface (which is good!).

Edit: solves #32

### CODE REVIEW

**Comment by jpetso** [comment]
I wonder if it's possible to do this without the extra copy (i.e. decoding directly into the array) and without removing the `inline` modifiers. I don't feel comfortable merging this in its current state, but it's awesome that there's an option for people who work with `std::array` types.

Sorry for not having put in much work upstream to provide better suggestions or make this work by default. I hope to get back to it eventually. Your contributions are appreciated :)

**Comment by theodelrieu** [comment]
IIRC I removed the inlines because they are already implied since the class is a template.

No problem, I'll try to look tonight on how the internals work.

**Comment by theodelrieu** [comment]
There is more work than what I thought...

In order to support arbitrary types and custom allocators, I think we should add a level of indirection (e.g. `cppcodec::encoder` and `cppcodec::decoder` which could be customized by users).

This is just a rough idea for now, I got inspired by this [talk](https://www.youtube.com/watch?v=WsUnnYEKPnI), there might be a better way.

**Comment by theodelrieu** [comment]
We could continue talking about that in the issue, meanwhile I'll close this PR.

**Pull request closed without merging**
