### PR TITLE
Packaging cleanups

### PR DESCRIPTION
**Pull request by SoapGentoo**
@jpetso 
I would like to package cppcodec for Gentoo in order to be able to build packages against it. It is Gentoo policy not to rely on bundled libraries. Adding pkg-config and using idiomatic CMake variables makes things easier for all distributions.

### CODE REVIEW

**Comment by jpetso** [comment]
Thanks, these commits look great and I'm happy to merge changes that make life better for packagers. Since it doesn't appear to break anything, you're making this a no-brainer for me (and CMake 2.8.5 is reasonable to assume these days). If I may ask, what packages would rely on it?

**Comment by jpetso** [comment]
I added a release at https://github.com/tplgy/cppcodec/releases/tag/v0.1 which you may use as source if you like. Thanks again for getting me there!

**Comment by SoapGentoo** [comment]
@jpetso The Nitrokey app https://github.com/Nitrokey/nitrokey-app uses it, and we need to unbundle the bundled version in order to independently fix problems on a system-wide level.

**Comment by jpetso** [comment]
Forgot to mention you in the list of contributors for the release. Sorry, and fixed!

**Pull request merged**
